ALTER TABLE menu_info DROP CONSTRAINT FK_EXPERT_TO_MENU_INFO;
ALTER TABLE expert DROP CONSTRAINT FK_USER_INFO_TO_EXPERT;
ALTER TABLE user_info DROP CONSTRAINT FK_AUTHORITY_TO_USER_INFO;
ALTER TABLE ads DROP CONSTRAINT FK_ADMINISTRATOR_TO_ADS;
commit;
[Error] Execution (49: 1): ORA-00001: unique constraint (JAMONG.PK_MENU_INFO) violated
[Error] Execution (400: 1): ORA-02291: integrity constraint (JAMONG.FK_ADMINISTRATOR_TO_ADS) violated - parent key not found